### ISSUE TITLE
Anime not Loading

### ISSUE THREAD

**Issue by skgupta507** [snoofox/AniPlay#1]
hello
i tried hosting it but the animes are not loading.
i think i need to add the anilist api key somewhere would u mind guiding me throught the process.
or if u have the .env template can u share it with me

**Comment by snoofox** [comment]
Hello, its because i forgot to add the backend in the repo, i'll update it ASAP!

**Comment by skgupta507** [comment]
Hi there @snoofox  your deployed site says "site not found" and the backend is not accessible for some reason

**Comment by snoofox** [comment]
I have removed my deployment, and i don't know what's the issue with backend linking of this repo. But u could find the backend repo on my profile, it's called  Aniplay-API
